services:
  frontend:
    build: frontend
    image: alskon/app-frontend
    ports:
      - 3001:3001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always
    networks:
      - app
    container_name: frontend

  backend:
    build: backend
    image: alskon/app-backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    restart: always
    networks:
      - app
    container_name: backend

networks:
  app:
    driver: bridge